import Head from 'next/head';
import React from 'react';
import ContactMe from '../components/ContactMe';
import Heading from '../components/Heading';

export default function About() {
  return (
    <>
      <Head>
        <title>Contact NazmuL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.png" />
      </Head>
      <Heading />
      <ContactMe />
    </>
  );
}
