import Head from 'next/head';
import React from 'react';
import Heading from '../components/Heading';
import HomePage from '../components/Home';

export default function Home() {
  return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading />
      <HomePage />
    </>
  );
}
