import Head from 'next/head';
import React from 'react';
import Heading from '../components/Heading';
import Portfolio from '../components/Portfolio';

export default function About() {
  return (
    <>
      <Head>
        <title>Portfolio NazmuL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/avatar.png" />
      </Head>
      <Heading />
      <Portfolio />
    </>
  );
}
